routes:
 -
  /:
    verb: GET
    response_headers:
     - Content-Type: application/json
    response_body:
    - status: 200
      body: Hello from Poser!
 -
  /posttest:
    verb: POST
    params:
      limit: 2
      offset: 25
    response_headers:
    - Content-Type: application/json
    response_body:
      status: 200
      body:
        results:
        - a6fd2ecc3a:
            name: Customer 1
            support_team: A9
          f4cd35662b:
            name: Customer 2
            support_team: A10
        count: 300
        next_offset: 28
